### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by whoamibruh** [wishmorningstar/animes4you#1]
1
![image](https://github.com/user-attachments/assets/469f1e49-554d-4f8a-b2b7-41fc5886b76d)
Call Stack
throwOnHydrationMismatch
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6789:0)
tryToClaimNextHydratableInstance
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6834:0)
updateHostComponent$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (15520:0)
beginWork$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (17355:0)
callCallback
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19443:0)
invokeGuardedCallbackImpl
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19492:0)
invokeGuardedCallback
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19567:0)
beginWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (25697:0)
performUnitOfWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24526:0)
workLoopConcurrent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24512:0)
renderRootConcurrent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24468:0)
performConcurrentWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23339:0)
workLoop
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (261:0)
flushWork
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (230:0)
performWorkUntilDeadline
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (534:0)
2
![image](https://github.com/user-attachments/assets/1d657ba9-a96d-4af6-b3ab-ee683e7ea61e)
Call Stack
finishConcurrentRender
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23516:0)
performConcurrentWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23394:0)
workLoop
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (261:0)
flushWork
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (230:0)
performWorkUntilDeadline
node_modules\next\dist\compiled\scheduler\cjs\scheduler.development.js (534:0)
3
![image](https://github.com/user-attachments/assets/0b565e0f-7e11-485f-8a1e-32d64ffe7d92)
Call Stack
throwOnHydrationMismatch
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6789:0)
tryToClaimNextHydratableInstance
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6834:0)
updateHostComponent$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (15520:0)
beginWork$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (17355:0)
callCallback
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19443:0)
invokeGuardedCallbackImpl
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19492:0)
invokeGuardedCallback
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (19567:0)
beginWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (25697:0)
performUnitOfWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24526:0)
workLoopSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24242:0)
renderRootSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24197:0)
performSyncWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23681:0)
flushSyncWorkAcrossRoots_impl
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9970:0)
flushSyncWorkOnAllRoots
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9928:0)
flushRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23735:0)
attemptSynchronousHydration
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (27167:0)
dispatchEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28658:0)
dispatchDiscreteEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28610:0)
4
![image](https://github.com/user-attachments/assets/104f8eb3-3614-404f-8549-4f0fdeaecef6)
Call Stack
throwOnHydrationMismatch
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6789:0)
tryToClaimNextHydratableInstance
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (6834:0)
updateHostComponent$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (15520:0)
beginWork$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (17355:0)
beginWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (25675:0)
performUnitOfWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24526:0)
workLoopSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24242:0)
renderRootSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24197:0)
performSyncWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23681:0)
flushSyncWorkAcrossRoots_impl
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9970:0)
flushSyncWorkOnAllRoots
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9928:0)
flushRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23735:0)
attemptSynchronousHydration
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (27167:0)
dispatchEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28658:0)
dispatchDiscreteEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28610:0)
5
![image](https://github.com/user-attachments/assets/bf0c3b64-8287-4be2-8e84-3b7848f2e2ea)
Call Stack
updateHostRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (15468:0)
beginWork$1
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (17338:0)
beginWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (25675:0)
performUnitOfWork
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24526:0)
workLoopSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24242:0)
renderRootSync
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (24197:0)
recoverFromConcurrentError
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23432:0)
performSyncWorkOnRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23693:0)
flushSyncWorkAcrossRoots_impl
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9970:0)
flushSyncWorkOnAllRoots
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (9928:0)
flushRoot
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (23735:0)
attemptSynchronousHydration
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (27167:0)
dispatchEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28658:0)
dispatchDiscreteEvent
node_modules\next\dist\compiled\react-dom\cjs\react-dom.development.js (28610:0)

**Comment by whoamibruh** [comment]
what did i do?
git clone repo
cd repo
cd inner folder
npm i next
npm run dev

**Comment by wishmorningstar** [comment]
Lol this project is discontinued

**Comment by whoamibruh** [comment]
:(
